variables: 
  BRANCH_NAME: "main"
  BOT_NAME: "MJAM"
  BOT_EMAIL: "mjam@update_readme.com"
  COMMIT_MESSAGE: "Auto-update README.md"
  PATH_TO_README: "../README.md"

.push: &push |
  git status
  lines=$(git status -s | wc -l)
  if [ $lines -gt 0 ];then
    git config user.name "${BOT_NAME}"
    git config user.email "${BOT_EMAIL}"
    git add $PATH_TO_README
    git commit -m "${COMMIT_MESSAGE}"
    git push -o ci.skip "https://${BOT_NAME}:${GIT_PUSH_TOKEN}@${CI_REPOSITORY_URL#*@}" $BRANCH_NAME
  fi 

update_docu:
  image: alpine:latest
  before_script:
    - apk add bash git
    - apk add --no-cache python3
    #- git config --global pull.rebase false
    #- git fetch
    - git checkout $BRANCH_NAME
    #- git pull --ff
    - cd ./src
  script:
    - python doc_to_md.py
    - *push