variables: 
  GIT_DEPTH: 1
  BRANCH_NAME: "test"
  BOT_NAME: "MJAM"
  BOT_EMAIL: "mjam@update_readme.com"
  COMMIT_MESSAGE: "Auto-update README.md"

.push: &push |
  git config --global user.name "${BOT_NAME}"
  git config --global user.email "${BOT_EMAIL}"
  git status
  git add .
  git commit -m "${COMMIT_MESSAGE}: ${CI_RUNNER_ID}"
  echo "git push -o ci.skip 'https://${BOT_NAME}:${GIT_PUSH_TOKEN}@${CI_REPOSITORY_URL#*@}' ${BRANCH_NAME}"
  git push -o ci.skip "https://${BOT_NAME}:${GIT_PUSH_TOKEN}@${CI_REPOSITORY_URL#*@}" $BRANCH_NAME
  fi

update_docu:
  image: alpine:latest  # python:latest
  before_script:
    - apk add bash git
    - apk add --no-cache python3
    - git config --global user.name "${BOT_NAME}"
    - git config --global user.email "${BOT_EMAIL}"
    - git fetch
    - git checkout $BRANCH_NAME
    - cd ./src
  script:
    - python doc_to_md.py
    - git add ../README.md
    - git commit -m "${COMMIT_MESSAGE}"
    - echo "git push -o ci.skip 'https://${BOT_NAME}:${GIT_PUSH_TOKEN}@${CI_REPOSITORY_URL#*@}' ${BRANCH_NAME}"
    - git push -o ci.skip "https://${BOT_NAME}:${GIT_PUSH_TOKEN}@${CI_REPOSITORY_URL#*@}" $BRANCH_NAME


