image: alpine:latest

pipelines:
  default:
    - step:
        name: update_docu
        .push: &push |
          lines=$(git status -s | wc -l)
          if [ $lines -gt 0 ];then
            git add ../README.md
            git commit -m "Auto-update README.md [skip ci]"
            echo "git push 'https://x-token-auth:${GIT_PUSH_TOKEN}@${REPO_URL}' ${BRANCH_NAME}"
            git push "https://x-token-auth:${GIT_PUSH_TOKEN}@${REPO_URL}" $BRANCH_NAME
          fi 
        script:
          - apk add bash git
          - apk add --no-cache python3
          - git config --global pull.rebase false
          #- git config --global user.name "${BOT_NAME}"
          #- git config --global user.email "${BOT_EMAIL}"
          - git fetch
          - git pull
          - cd ./src
          - echo "Update README.md"
          - python3 doc_to_md.py
          - *push