image: alpine:latest

pipelines:
  branches:
    main:
      - step:
          name: update_docu
          .prep: &prep |
            apk add bash git
            apk add --no-cache python3
            git fetch
            cd ./src
          .push: &push |
            lines=$(git status -s | wc -l)
            if [ $lines -gt 0 ];then
              git add ../README.md
              git commit -m "Auto-update README.md [skip ci]"
              git push
            fi 
          script:
            - *prep
            - python3 doc_to_md.py -f "../README.md"
            - *push
