image: alpine:latest

pipelines:
  default:
    - step:
        name: update_docu
        .push: &push |
          git status
          lines=$(git status -s | wc -l)
          if [ $lines -gt 0 ];then
            git config --global user.name "${BOT_NAME}"
            git config --global user.email "${BOT_EMAIL}"
            git add ../README.md
            git commit -m "Auto-update README.md"
            git push -o ci.skip "https://${BOT_NAME}:${GIT_PUSH_TOKEN}@${BITBUCKET_GIT_SSH_ORIGIN#*@}" $BRANCH_NAME
          fi 
        script:
          - apk add bash git
          - apk add --no-cache python3
          - git config --global pull.rebase false
          - git fetch
          - git checkout $BRANCH_NAME
          - git pull
          - cd ./src
          - python3 doc_to_md.py
          - *push