variables:
  BOT_NAME: "AUTO-UPDATE-README"
  BOT_EMAIL: "doc@update_readme.com"
  COMMIT_MESSAGE: "Auto-update README.md"
  PATH_TO_README: "README.md"
  ROOT_DIR: ""
  EXCLUDED_MODULES: ""
  SELECTED_MODULES: ""
  SEPARATED: "true"

.push: &push |
  git status
  lines=$(git status -s | wc -l)
  if [ $lines -gt 0 ];then
    git config --global user.name "${BOT_NAME}"
    git config --global user.email "${BOT_EMAIL}"
    git add $PATH_TO_README
    git commit -m "${COMMIT_MESSAGE}"
    git push -o ci.skip "https://${BOT_NAME}:${GIT_PUSH_TOKEN}@${CI_REPOSITORY_URL#*@}" $CI_COMMIT_BRANCH
  fi

.exec: &exec |
  cmd="doc_to_md.py -f $PATH_TO_README"
  if [[ ! -z $EXCLUDED_MODULES ]]; then
    cmd="$cmd -e $EXCLUDED_MODULES"
  elif [[ ! -z $SELECTED_MODULES ]]; then
    cmd="$cmd -m $SELECTED_MODULES"
  fi
  if [ ! -z $ROOT_DIR ]; then
    cmd="$cmd -r $ROOT_DIR"
  fi
  if [ $SEPARATED = "true" ]; then
    cmd="$cmd --separated"
  fi
  echo $cmd
  python $cmd
  rm doc_to_md.py

update_docu:
  image: alpine:latest
  before_script:
    - apk add bash git
    - apk add --no-cache python3
    - git clone 'https://github.com/ziselsberger/doc_to_readme.git'
    - git config --global pull.rebase false
    - git checkout $CI_COMMIT_BRANCH
    - git pull
    - cp ./doc_to_readme/src/doc_to_md/doc_to_md.py .
    - rm -rf doc_to_readme
  script:
    - *exec
    - *push
