variables: 
  BRANCH_NAME: "main"
  BOT_NAME: "AUTO-UPDATE-README"
  BOT_EMAIL: "doc@update_readme.com"
  COMMIT_MESSAGE: "Auto-update README.md"
  PATH_TO_README: "README.md"
  EXCLUDED_MODULES: ""
  SELECTED_MODULES: ""

.push: &push |
  git status
  lines=$(git status -s | wc -l)
  if [ $lines -gt 0 ];then
    git config --global user.name "${BOT_NAME}"
    git config --global user.email "${BOT_EMAIL}"
    git add $PATH_TO_README
    git commit -m "${COMMIT_MESSAGE}"
    git push -o ci.skip "https://${BOT_NAME}:${GIT_PUSH_TOKEN}@${CI_REPOSITORY_URL#*@}" $BRANCH_NAME
  fi

update_docu:
  image: alpine:latest
  before_script:
    - apk add bash git
    - apk add --no-cache python3
    - git clone 'https://github.com/ziselsberger/doc_to_readme.git'
    - git config --global pull.rebase false
    - git checkout $BRANCH_NAME
    - git pull
    - cp ./doc_to_readme/src/doc_to_md.py .
    - rm -rf doc_to_readme
    - env
  script:
    - if $EXCLUDED_MODULES; then python doc_to_md.py -f $PATH_TO_README -e $EXCLUDED_MODULES
    - if $SELECTED_MODULES; then python doc_to_md.py -f $PATH_TO_README -m $SELECTED_MODULES
    - if not ($EXCLUDED_MODULES && $SELECTED_MODULES); then python doc_to_md.py -f $PATH_TO_README
    - rm doc_to_md.py
    - *push
